#!/usr/bin/env python3
"""
Derive each article's "last updated" date from git and hand it to Jekyll.

The date on a help page has to answer one question honestly: *was this article
brought up to date after the last version push?* A site-wide build stamp cannot
answer it — it prints today's date on an article nobody has touched since July,
which is precisely the lie the date is there to catch. So the only source of
truth is the article's own last commit:

    git log -1 --format=%cI -- _articles/<name>.md

This writes `_data/last_updated.yml`, which the layouts read. The file is
GENERATED, never committed (see .gitignore) — a committed copy would freeze the
moment it went stale, which is the same lie wearing a different hat.

    python3 tools/last_updated.py            # write _data/last_updated.yml
    python3 tools/last_updated.py --print    # show what it would write

Run it before `jekyll build` (the Pages workflow does; so does tools/preview.py).
The checkout must have full history — `fetch-depth: 0` — or there are no commit
dates to read and this exits nonzero rather than inventing one.
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).parent.parent
ARTICLES = ROOT / "_articles"
DATA = ROOT / "_data" / "last_updated.yml"


def git(*args, root=ROOT):
    """Run git in `root`; return stdout stripped, or None if git itself failed."""
    proc = subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return None
    return proc.stdout.strip()


def front_matter(path):
    m = re.match(r"^---\n(.*?)\n---\n", path.read_text(encoding="utf-8"), re.S)
    return m.group(1) if m else ""


def field(fm, name):
    m = re.search(rf"^{name}:\s*(.*)$", fm, re.M)
    return m.group(1).strip().strip('"') if m else None


def slug_of(path):
    """An article's slug drives its URL, so the layouts key on it, not the filename."""
    return field(front_matter(path), "slug") or path.stem


def is_published(path):
    """Articles held by the review gate carry `published: false` and never reach
    the live site. Editing one must not move the site-wide date — a reader would
    see "updated today" with nothing on the site actually different."""
    return field(front_matter(path), "published") != "false"


def article_dates(root=ROOT):
    """slug -> ISO8601 commit date of that article's most recent change.

    Returns (dates, published, problems); `published` is the subset of slugs
    that actually reach the live site, which is what the site-wide date is
    computed from. A file with no commit date is a problem, never a guess: an
    unborn or shallow-cloned repo must fail the build loudly.
    """
    articles = root / "_articles"
    dates, published, problems = {}, set(), []

    if git("rev-parse", "--git-dir", root=root) is None:
        problems.append(f"{root} is not a git repository — commit dates cannot be derived")
        return dates, published, problems

    if git("rev-parse", "--is-shallow-repository", root=root) == "true":
        problems.append(
            "the checkout is SHALLOW — per-file history is missing, so dates would be "
            "wrong or absent. Check out with fetch-depth: 0."
        )

    for path in sorted(articles.glob("*.md")):
        rel = str(path.relative_to(root))
        when = git("log", "-1", "--format=%cI", "--", rel, root=root)
        if not when:
            problems.append(
                f"{rel}: no commit date — the file is untracked or its history is "
                f"missing, and this tool will not substitute today's date for it"
            )
            continue
        slug = slug_of(path)
        dates[slug] = when
        if is_published(path):
            published.add(slug)

    if not dates and not problems:
        problems.append(f"no articles found in {articles}")
    elif dates and not published:
        problems.append("every article is held by the review gate — no live content to date")

    return dates, published, problems


def site_date(dates, published):
    """When the help a reader can actually see last changed."""
    return max(when for slug, when in dates.items() if slug in published)


def render(dates, published):
    """The data file, written by hand so the site needs no YAML dependency."""
    lines = [
        "# GENERATED by tools/last_updated.py — do not edit, do not commit.",
        "# Each date is that article's own last commit date. The site date is the",
        "# most recent across PUBLISHED articles only — editing a held draft",
        "# changes nothing a reader can see, so it must not move the site date.",
        "",
        f'site: "{site_date(dates, published)}"',
        "articles:",
    ]
    lines += [f'  {slug}: "{when}"' for slug, when in sorted(dates.items())]
    return "\n".join(lines) + "\n"


def main():
    dates, published, problems = article_dates()

    if problems:
        for p in problems:
            print(f"error: {p}", file=sys.stderr)
        return 1

    text = render(dates, published)

    if "--print" in sys.argv:
        print(text, end="")
        return 0

    DATA.parent.mkdir(exist_ok=True)
    DATA.write_text(text, encoding="utf-8")
    print(f"wrote {DATA.relative_to(ROOT)} — {len(dates)} articles "
          f"({len(published)} published), site last updated "
          f"{site_date(dates, published)[:10]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
